apiVersion: v1
kind: Service
metadata:
  name: {{ include "novasight.fullname" . }}-dagster-web
  labels:
    {{- include "novasight.labels" . | nindent 4 }}
    app.kubernetes.io/component: dagster-web
spec:
  type: {{ .Values.dagster.web.service.type }}
  ports:
    - name: http
      port: {{ .Values.dagster.web.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "novasight.selectorLabels" (dict "ctx" . "component" "dagster-web") | nindent 4 }}
