"""Declarative base for all control-plane ORM models.

A shared ``MetaData`` with an explicit naming convention is used so that
constraints and indexes get deterministic names. Alembic relies on those names
to emit reversible migrations; without the convention, autogenerated
``downgrade()`` operations cannot reliably reference unnamed constraints.

All control-plane tables live in the same metadata so that a single
``Base.metadata.create_all`` (tests) and a single Alembic ``target_metadata``
(migrations) describe the whole schema.
"""
from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Deterministic names for indexes/constraints — keeps migrations reproducible.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Common base for every control-plane model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class TimestampMixin:
    """Adds ``created_at`` / ``updated_at`` columns, defaulted in the database.

    Server-side defaults (``func.now()``) compile per-dialect, so the same model
    works against Postgres (production) and SQLite (tests) without change.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
