apiVersion: v1
kind: Secret
metadata:
  name: {{ include "analytica.secretName" . }}
  labels:
    {{- include "analytica.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := (.Values.secrets | default dict) }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
