"""Render semantic-model definitions into Cube model files (#8).

## Per-tenant isolation via repositoryFactory

Cube loads each tenant's model files from a **per-tenant directory** through the
``repositoryFactory`` in ``data-platform/semantic/config/cube.js``: a request scoped to
``clickhouse_db`` only ever sees the shared static cubes plus the files under
``<root>/<clickhouse_db>/``. Because isolation is at the directory level, the generated
cubes need no in-file guard — one tenant's catalog is never even parsed for another.

The codegen writes a single ``models.js`` per tenant holding all that tenant's cubes;
the service rewrites it on every change. ``sql_table`` still resolves the tenant DB at
compile time from ``COMPILE_CONTEXT.securityContext.clickhouse_db`` (per request).

## Safety

Everything interpolated is either a validated identifier (member/column names,
``base_table`` — see ``schemas.semantic_model``) or JSON-encoded (titles). There is no
path for arbitrary SQL to reach the generated file.
"""
from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path

from app.schemas.semantic_model import DimensionDef, MeasureDef, SemanticModelConfig

# NovaSight measure type → Cube measure type.
_MEASURE_TYPE: dict[str, str] = {
    "count": "count",
    "sum": "sum",
    "avg": "avg",
    "min": "min",
    "max": "max",
    "count_distinct": "countDistinct",
}

# One generated file per tenant, inside that tenant's directory.
TENANT_MODELS_FILENAME = "models.js"

_HEADER = (
    "// AUTO-GENERATED by NovaSight semantic codegen — do not edit by hand.\n"
    "// One file per tenant; loaded only for this tenant via repositoryFactory.\n"
)


@dataclass(frozen=True)
class CubeModelInput:
    """One model to render: its name, serving table, and member definitions."""

    name: str
    base_table: str
    config: SemanticModelConfig


def tenant_model_relpath(clickhouse_db: str) -> str:
    """Path of a tenant's generated file relative to the model root."""
    return f"{clickhouse_db}/{TENANT_MODELS_FILENAME}"


def render_tenant_models(models: list[CubeModelInput]) -> str:
    """Render a tenant's models into one Cube JS file (no guard — dir-isolated).

    With no models the file is just the header comment, which harmlessly clears the
    tenant's cubes on the next compile.
    """
    lines: list[str] = [_HEADER]
    for model in models:
        lines.append(_render_cube(model))
    return "\n".join(lines) + "\n"


def write_tenant_models(model_dir: str, clickhouse_db: str, content: str) -> Path:
    """Write a tenant's rendered file atomically to ``<model_dir>/<db>/models.js``.

    The per-tenant directory is created if missing. Atomic (write-temp-then-replace)
    so Cube never reads a half-written file. Returns the written path.
    """
    directory = Path(model_dir) / clickhouse_db
    directory.mkdir(parents=True, exist_ok=True)
    target = directory / TENANT_MODELS_FILENAME
    tmp = target.with_suffix(".js.tmp")
    tmp.write_text(content, encoding="utf-8")
    os.replace(tmp, target)
    return target


# ---------------------------------------------------------------------------
# Internals
# ---------------------------------------------------------------------------


def _render_cube(model: CubeModelInput) -> str:
    # name + base_table are validated identifiers (schemas.semantic_model), so they
    # are safe inside the backtick templates below.
    measures = ",\n".join(_render_measure(m) for m in model.config.measures)
    dimensions = ",\n".join(_render_dimension(d) for d in model.config.dimensions)
    return (
        f"cube(`{model.name}`, {{\n"
        f"  sql_table: `\\`${{COMPILE_CONTEXT.securityContext.clickhouse_db}}\\`."
        f"\\`{model.base_table}\\``,\n"
        f"  measures: {{\n{measures}\n  }},\n"
        f"  dimensions: {{\n{dimensions}\n  }},\n"
        f"}});"
    )


def _render_measure(m: MeasureDef) -> str:
    parts = [f"type: {json.dumps(_MEASURE_TYPE[m.type])}"]
    if m.sql is not None:
        parts.append(f"sql: {json.dumps(m.sql)}")
    if m.title:
        parts.append(f"title: {json.dumps(m.title)}")
    if m.description:
        parts.append(f"description: {json.dumps(m.description)}")
    return f"    {m.name}: {{ {', '.join(parts)} }}"


def _render_dimension(d: DimensionDef) -> str:
    parts = [f"sql: {json.dumps(d.sql)}", f"type: {json.dumps(d.type)}"]
    if d.title:
        parts.append(f"title: {json.dumps(d.title)}")
    if d.description:
        parts.append(f"description: {json.dumps(d.description)}")
    if d.primary_key:
        parts.append("primaryKey: true")
    # Expose every dimension (primaryKey members are hidden by default in Cube).
    parts.append("public: true")
    return f"    {d.name}: {{ {', '.join(parts)} }}"
