"""Standalone FastMCP server entrypoint (``python -m app.mcp.server``).

Builds a :class:`FastMCP` app that exposes the three grounded chat tools to
external MCP clients and forwards each call to the backend API (see the package
and :mod:`app.mcp.backend_client` docstrings for the security model).

Run it as its own process / compose role::

    python -m app.mcp.server

The tool *names* and *descriptions* are imported from the in-process chat service
so the external MCP surface stays in lockstep with what the internal chat loop
exposes (one source of truth). Their input schemas are generated by FastMCP from
the handler signatures below, which mirror the chat tools' inputs.
"""
from __future__ import annotations

import logging
import sys
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from typing import Any

from mcp.server.fastmcp import Context, FastMCP
from mcp.server.fastmcp.exceptions import ToolError
from mcp.server.transport_security import TransportSecuritySettings

from app.ai.chat.service import LIST_MODELS, NL_TO_SQL, QUERY_MODEL, TOOL_SPECS
from app.core.config import McpSettings, Settings, get_settings
from app.core.logging import configure_logging
from app.mcp.backend_client import AnalyticsBackendClient, BackendError

logger = logging.getLogger(__name__)

# name -> advertised description, taken from the canonical chat tool specs so the
# MCP tools never drift from the in-process ones.
_DESCRIPTIONS: dict[str, str] = {spec.name: spec.description for spec in TOOL_SPECS}


def _authorization(ctx: Context[Any, Any, Any]) -> str:
    """Return the caller's raw ``Authorization`` header, or fail closed.

    The MCP server forwards this header to the backend, which is the single
    auth/tenancy boundary (golden rule 2). A missing header is a ``ToolError`` —
    the server never defaults or invents a tenant identity. Only HTTP transports
    (streamable-http / sse) carry headers; under stdio there is no request, so the
    same fail-closed error is returned.
    """
    request = getattr(ctx.request_context, "request", None)
    header = request.headers.get("authorization") if request is not None else None
    if not header:
        raise ToolError(
            "Missing bearer token. Send an 'Authorization: Bearer <token>' header "
            "(the same tenant token used by the NovaSight API)."
        )
    return str(header)


def _cap_rows(
    result: dict[str, Any], *, max_rows: int
) -> dict[str, Any]:
    """Truncate a ``{columns, rows, row_count}`` result to ``max_rows``.

    Mirrors the in-process chat loop's row cap so a large result can't blow the MCP
    client's context window. ``row_count`` is preserved as the backend reported it
    and a ``truncated`` flag is added when rows were dropped.
    """
    rows = result.get("rows")
    if isinstance(rows, list) and len(rows) > max_rows:
        return {**result, "rows": rows[:max_rows], "truncated": True}
    return {**result, "truncated": False}


def build_server(
    settings: McpSettings, *, client: AnalyticsBackendClient | None = None
) -> FastMCP:
    """Assemble the FastMCP server and its three grounded, proxying tools.

    Args:
        settings: The ``settings.mcp`` group (transport, limits, backend URL).
        client: An optional pre-built backend client. When ``None`` (production),
            one is constructed from ``settings``; tests inject a client backed by a
            mock transport. When injected, the ``backend_base_url`` check is skipped
            (the client already encapsulates the base URL).

    Raises:
        ValueError: if no ``client`` is injected and ``settings.backend_base_url``
            is empty — the server cannot proxy without a backend, so it fails
            closed at build.
    """
    if client is None:
        if not settings.backend_base_url:
            raise ValueError(
                "MCP__BACKEND_BASE_URL is required (e.g. http://api:8000/api/v1) — "
                "the MCP server proxies every tool call to that API."
            )
        client = AnalyticsBackendClient(
            settings.backend_base_url, timeout=settings.request_timeout_seconds
        )
    backend = client  # bound non-None reference for the closures below

    @asynccontextmanager
    async def lifespan(_server: FastMCP) -> AsyncIterator[None]:
        """Release the backend HTTP connection pool on shutdown.

        In stateless HTTP mode FastMCP runs this lifespan *per request*, so closing
        the shared, process-lifetime backend pool here would kill it after the first
        request — the next tool call then fails with "client has been closed". Only
        close when a single lifespan spans the whole process (stdio / sse); under
        stateless HTTP the pool is released when the process exits.
        """
        try:
            yield
        finally:
            if not settings.stateless:
                await backend.aclose()

    security = (
        TransportSecuritySettings(
            enable_dns_rebinding_protection=True,
            allowed_hosts=settings.allowed_hosts,
            allowed_origins=settings.allowed_origins,
        )
        if settings.allowed_hosts or settings.allowed_origins
        else None
    )

    mcp = FastMCP(
        name="NovaSight Analytics",
        instructions=(
            "Grounded, tenant-scoped analytics over a governed semantic layer. "
            "Authenticate with the NovaSight tenant bearer token. Call "
            f"{LIST_MODELS} first to discover governed measures and dimensions, "
            f"then {QUERY_MODEL} for structured lookups or {NL_TO_SQL} for ad-hoc "
            "questions. Every figure traces to a tool result; nothing is invented."
        ),
        host=settings.host,
        port=settings.port,
        streamable_http_path=settings.path,
        stateless_http=settings.stateless,
        transport_security=security,
        lifespan=lifespan,
    )

    @mcp.tool(name=LIST_MODELS, description=_DESCRIPTIONS[LIST_MODELS])
    async def list_semantic_models(ctx: Context[Any, Any, Any]) -> list[dict[str, Any]]:
        authorization = _authorization(ctx)
        try:
            return await backend.list_semantic_models(authorization)
        except BackendError as exc:
            raise ToolError(exc.message) from exc

    @mcp.tool(name=QUERY_MODEL, description=_DESCRIPTIONS[QUERY_MODEL])
    async def query_semantic_model(
        ctx: Context[Any, Any, Any],
        measures: list[str] | None = None,
        dimensions: list[str] | None = None,
        limit: int | None = None,
    ) -> dict[str, Any]:
        measures = measures or []
        dimensions = dimensions or []
        if not measures and not dimensions:
            raise ToolError("Provide at least one measure or dimension.")
        authorization = _authorization(ctx)
        try:
            result = await backend.query_semantic_model(
                authorization, measures=measures, dimensions=dimensions, limit=limit
            )
        except BackendError as exc:
            raise ToolError(exc.message) from exc
        return _cap_rows(result, max_rows=settings.max_tool_rows)

    @mcp.tool(name=NL_TO_SQL, description=_DESCRIPTIONS[NL_TO_SQL])
    async def nl_to_sql(ctx: Context[Any, Any, Any], question: str) -> dict[str, Any]:
        if not question.strip():
            raise ToolError("Provide a non-empty question.")
        authorization = _authorization(ctx)
        try:
            result = await backend.nl_to_sql(authorization, question=question)
        except BackendError as exc:
            raise ToolError(exc.message) from exc
        return _cap_rows(result, max_rows=settings.max_tool_rows)

    return mcp


def main() -> None:
    """Process entrypoint: configure logging, build the server, run the transport."""
    settings: Settings = get_settings()
    configure_logging(level=settings.log_level)
    try:
        server = build_server(settings.mcp)
    except ValueError as exc:
        logger.error("MCP server cannot start: %s", exc)
        sys.exit(1)

    logger.info(
        "Starting MCP server: transport=%r host=%r port=%d path=%r backend=%r",
        settings.mcp.transport,
        settings.mcp.host,
        settings.mcp.port,
        settings.mcp.path,
        settings.mcp.backend_base_url,
    )
    server.run(transport=settings.mcp.transport)  # type: ignore[arg-type]


if __name__ == "__main__":
    main()
